### ISSUE TITLE
ml configure summarize fails

### ISSUE THREAD

**Issue by gjwgit** [shashank-gv/hugging#1]
```
gjw@hubert:~$ ml configure summarize

*** Installing Python package pytorch by pip into
  /home/gjw/.mlhub/summarize/.python

Do you want to pip install pytorch [Y/n]? 
Collecting pytorch
  Downloading pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py) ... error
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
  Running setup.py install for pytorch ... error
mlhub: An error was encountered:
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8n6snig5/pytorch_64ca1a15f20e4c2da2769d2641a92c0e/setup.py", line 15, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
  error: subprocess-exited-with-error
  
  × Running setup.py install for pytorch did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8n6snig5/pytorch_64ca1a15f20e4c2da2769d2641a92c0e/setup.py", line 11, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pytorch

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by shashank-gv** [comment]
This was an error in the yaml file trying to pip install pytorch instead of torch. Should be fixed now.

**Comment by gjwgit** [comment]
Now works. Thanks.
